### PR TITLE
Install OTK using a job

### PR DESCRIPTION
**Pull request by APIM-KiranVaddadi**
**Description of the change**

Install OTK using a job

**Benefits**

Seamless installation and upgrade of OTK.

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by Gazza7205 — COMMENTED** [review]
@APIM-KiranVaddadi - env shouldn't be used directly in the job spec where they have to be declared in values.yaml (especially for db passwords).

The best option would be a config file that is mounted via an existingSecret - this allows use of the Secret Store CSI Driver and existing Kubernetes Secrets.

**Comment by APIM-KiranVaddadi** [comment]
> @APIM-KiranVaddadi - env shouldn't be used directly in the job spec where they have to be declared in values.yaml (especially for db passwords).
> 
> The best option would be a config file that is mounted via an existingSecret - this allows use of the Secret Store CSI Driver and existing Kubernetes Secrets.

Its addressed now.

**Comment by Gazza7205** [comment]
> > @APIM-KiranVaddadi - env shouldn't be used directly in the job spec where they have to be declared in values.yaml (especially for db passwords).
> > The best option would be a config file that is mounted via an existingSecret - this allows use of the Secret Store CSI Driver and existing Kubernetes Secrets.
> 
> Its addressed now.

This looks like it requires gateway admin username/password?
https://github.com/APIM-KiranVaddadi/apim-charts/blob/otk_install_job/charts/gateway/templates/otk-install-job.yaml

Is the management flag used to avoid ephemeral use cases?

**Comment by APIM-KiranVaddadi** [comment]
> > > @APIM-KiranVaddadi - env shouldn't be used directly in the job spec where they have to be declared in values.yaml (especially for db passwords).
> > > The best option would be a config file that is mounted via an existingSecret - this allows use of the Secret Store CSI Driver and existing Kubernetes Secrets.
> > 
> > 
> > Its addressed now.
> 
> This looks like it requires gateway admin username/password? https://github.com/APIM-KiranVaddadi/apim-charts/blob/otk_install_job/charts/gateway/templates/otk-install-job.yaml
> 
> Is the management flag used to avoid ephemeral use cases?

It does need username/password. Updated the job to get them from secret. Also removed the dependency on management to be enabled. The job needs only restman to be enabled.

**Review by Gazza7205 — APPROVED** [review]
Looks good to me

**Pull request merged**
