### PR TITLE
[charts/druid, charts/gateway, charts/gateway-otk, charts/portal] Allow PodDisruptionBudget configuration

### PR DESCRIPTION
**Pull request by jmmAVGO**
**Description of the change**

Permits the use of helm chart optionis to support HA-deployments by adding PodDisruptionBudget objects

**Benefits**

Customers will be able to ensure a minimum number of pods running for each service (or maximum number of unavailable pods)

**Drawbacks**

Uncertain of values approach for minio, especially; also kafka+zookeper, since rely on quorums. Note: pdbs disabled by default in all configurations.

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by jmmAVGO** [comment]
@Gazza7205 can i get your feedback on this? would love to see what my next steps are.
(edit: or @gvermeulen7205 , whichever i should be usinig, sorry!)

**Review by Gazza7205 — COMMENTED** [review]
I think this should be replaced
```
spec:
  minAvailable: {{ .Values.x.pdb.minAvailable }}
  maxUnavailable: {{ .Values.x.pdb.maxUnavailable }}
```
with something like this
```
spec:
  {{- if .Values.x.pdb.minAvailable }}
  minAvailable: {{ .Values.x.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.x.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.x.pdb.maxUnavailable }}
  {{- end }}
```
That will remove the need to explicitly set min or max unavailable where only one is needed

This
```
pdb:
  create: false
  maxUnavailable: ""  <== this is also an integer so this could be confusing
  minAvailable: 4
```
becomes this
```
pdb:
  create: false
  minAvailable: 4
 # maxUnavailable: 0
   
```

Labels should also be included

**Comment by jmmAVGO** [comment]
@Gazza7205 Sandeep is sayinig "stable" may not be the correct branch target here ; can you confirm  Ishould change my branch to "develop"?

**Comment by Gazza7205** [comment]
> @Gazza7205 Sandeep is sayinig "stable" may not be the correct branch target here ; can you confirm Ishould change my branch to "develop"?

Given this affects more than one Chart and adds functionality that is not enabled by default I don't have a strong opinion against merging this into stable. There is a process for develop that should be followed if Sandeep has requested that. I'm not quite sure where it fits though.

**Comment by jmmAVGO** [comment]
@Gazza7205 I've attempted to address your concerns - I've made the miin/max conditioinals, and added labels to the PDBs (I'm assuming that was that you meant).

**Comment by jmmAVGO** [comment]
@APIM-KiranVaddadi @SatishKoney-BRCM doo you have feelings/opinioins on the target branch? @Gazza7205 forgive me for trying to be ignorant about it all just a little biit longer, but I don't know how you all do branches. Sandeep was certaiin 'stable' was not the correct target branch, but I am much less informed (and therefore less opinioinated)

Also, if I haven't mentioned it before, my keyboard has problems, and Broadcom isn't going to fix it. I've stopped correcting the  typos; there are simply too many.

**Comment by jmmAVGO** [comment]
@Gazza7205 @dev2020-sr I think this PR is still good to go (at least agaiinst this branch) and valuable. I donn't really understand the different product/branches here; can you two please work out which branch this should be against and let me know? IIf necessary, II can rebase and briing it up to date. IIf not, I'm happy to merge as-is.

**Comment by jmmAVGO** [comment]
Setting do not merge on this. Going to come back at this with separate PRs for each product.

**Comment by jmmAVGO** [comment]
Superseded by #211 , #212 , #222
Closing

**Pull request closed without merging**
