### PR TITLE
US725489: Changes to use mysql 8.0.22

### PR DESCRIPTION
**Pull request by as666499**
**Description of the change**

changes to use bitnami mysql(8.0.22) chart
updated image tags
updated values for new mysql chart

**Benefits**

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by as666499** [comment]
Creating a new PR with correct branch. @Gazza7205 @APIM-KiranVaddadi.
Copying review comment from earlier PR.
The Readme.md will need to be updated to reflect the new MySQL configuration.

The securityContext configuration is specific to the stable mysql chart - if this is going to be referenced it needs to be up to date. https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml

Troubleshooting (Readme.md) - the Bitnami MySQL Chart uses statefulsets, this means that the mysql-root and replication passwords become invalid if the Chart is deleted and reinstalled without removing the mysql volumes. See RabbitMQ troubleshooting.

Chart.yaml - appVersion + version need to be bumped.

**Comment by as666499** [comment]
> The Readme.md will need to be updated to reflect the new MySQL configuration.
> 
Checking which configuration parameters needs to be specified as it has a large number of params. Any things to keep in mind while picking some parameters? Also, planning to mention the url to the mysql chart page which has all the params.

> The securityContext configuration is specific to the stable mysql chart - if this is going to be referenced it needs to be up to date. https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml
>
Removed securityContext configuration, comments & ineffective params which are specifying default values to keep the configuration minimum.

> Troubleshooting (Readme.md) - the Bitnami MySQL Chart uses statefulsets, this means that the mysql-root and replication passwords become invalid if the Chart is deleted and reinstalled without removing the mysql volumes. See RabbitMQ troubleshooting.
> 
Going to test and update it.

> Chart.yaml - appVersion + version need to be bumped.
done.

**Review by Gazza7205 — COMMENTED** [review]
Have the image tags been updated to 5.0.cr1?

**Comment by as666499** [comment]
@Gazza7205 @APIM-KiranVaddadi  updated image tags & documentation

**Review by Gazza7205 — COMMENTED** [review]
Looks good to me - the mysql replication password should be settable.

**Review by APIM-KiranVaddadi — APPROVED** [review]
LGTM

**Pull request merged**
