### PR TITLE
[charts/portal] Add env var HTTPD_USE_SSL_CERT_CHAIN to use certificate chain for di…

### PR DESCRIPTION
**Pull request by acheuk**
…spatcher.

**Description of the change**

Add environment variable to show certificate chain for dispatcher.

**Benefits**

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by melil02** [comment]
@scottchc1 do you think for those edge cases we need to expose it as separate variable or use additional values? Or not document it at all? I think we should introduce HTTPD_USE_SSL_CERT_CHAIN standalone in this case

**Comment by scottchc1** [comment]
i don't know enough about what use case this change serves. maybe @Gazza7205 can review?
i would treat additionalEnv meant to be optional, and should be empty in most standard deployment. so if this env must exist and have a default value (doesn't matter true or false, as long as the env key need to exist), then declare it explicitly.

**Review by Gazza7205 — CHANGES_REQUESTED** [review]
If this is an optional variable using additionalEnv should be fine. If this is mandatory then adding and documenting it makes sense. 

@acheuk - could you clarify?

**Comment by acheuk** [comment]
I think this should be an optional variable. @melil02, can you confirm?

**Comment by melil02** [comment]
Agree, lets not expose it for now.

**Comment by Gazza7205** [comment]
@acheuk - should we close this PR or do you want to keep it open?

**Comment by acheuk** [comment]
Closing this PR per comment above.

**Pull request closed without merging**
