### PR TITLE
[charts/gateway] Pmtagger tolerations

### PR DESCRIPTION
**Pull request by scottchc1**
**Description of the change**
add tolerations to pmtagger

**Benefits**
enable assigning pmtagger pod to designated node pool with taints

**Drawbacks**
none

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by Gazza7205 — APPROVED** [review]
Looks good to me - we should move this to .Values.pmtagger.affinity/tolerations/nodeSelector, etc. before this goes to stable.

**Comment by scottchc1** [comment]
@Gazza7205 i was intending to reuse the same nodeSeletor and tolerations values from gateway; that's why there is no additional values file update.
please confirm if reuse is ok or if you prefer separate values?
e.g. `values.tolerations` applies to both gateway and pmtagger, or
`values.tolerations` - gateway only, then `values.pmtagger.tolerations`

**Comment by Gazza7205** [comment]
> @Gazza7205 i was intending to reuse the same nodeSeletor and tolerations values from gateway; that's why there is no additional values file update. please confirm if reuse is ok or if you prefer separate values? e.g. `values.tolerations` applies to both gateway and pmtagger, or `values.tolerations` - gateway only, then `values.pmtagger.tolerations`

I think separate nodeSelector/tolerations given it's a separate optional deployment make sense.

#184 has that update - if you're happy to proceed I'll merge it into this branch.

**Comment by scottchc1** [comment]
merged #184 and added another fix in the if conditions.
please do a final review and merge this pr if ok

**Pull request merged**
