### PR TITLE
Updated max allowed packet

### PR DESCRIPTION
**Pull request by DamandeepToor**
**Description of the change**

Updated max_allowed_packet=20M to match the default value of CWP serverModuleFile.upload.maxSize

**Benefits**

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by hydak** [comment]
@DamandeepToor does this change need to happen for Portal as well, or just for Gateway?

**Comment by DamandeepToor** [comment]
@hydak , as the issue was in TSSG so reverted the changes for Portal

**Review by Gazza7205 — CHANGES_REQUESTED** [review]
Each Chart that changes needs to have its version bumped for the release pipeline.

/charts/*chartname*/Chart.yaml ==> version

**Review by hydak — APPROVED** [review]

**Review by cuisimon — APPROVED** [review]
LGTM.

**Review by Gazza7205 — APPROVED** [review]

**Comment by scottchc1** [comment]
merged on behalf of @hydak
@DamandeepToor remember to mark the pr checklist next time

**Pull request merged**
