### PR TITLE
US939749: Remove PSSG

### PR DESCRIPTION
**Pull request by acheuk**
**Description of the change**
Remove PSSG dependency and clean up

**Benefits**

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by melil02** [comment]
Looks good to me. :)

**Review by markgxchen — APPROVED** [review]
LGTM

**Comment by melil02** [comment]
It complains about druid charts and we haven't touched those.

**Review by melil02 — APPROVED** [review]
LGTM

**Pull request merged**
