### PR TITLE
US696627: Add SSL settings for DB

### PR DESCRIPTION
**Pull request by mohsinkhanbrcm**
**Description of the change**

- Adding the essential SSL props from  https://cawiki.ca.com/display/APIMPortal/F103659+Configurable+DB+connection+settings+for+Portal+DB to the deployment props.
- Wiki for deploying portal on k8s @ https://cawiki.ca.com/pages/viewpage.action?pageId=864712296

Details in the ticket: 
- [US696627](https://rally1.rallydev.com/#/detail/userstory/423754615636?fdp=true)

**Benefits**

- Ability to pass in the SSL settings for DB connections

**Drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by melil02** [comment]
@mohsinkhanbrcm please clean up new line changes

**Review by Gazza7205 — CHANGES_REQUESTED** [review]
Please follow the Pull request requirements.

Specifically -
* Update the Chart Versions (druid + portal) - this is required for the release process.
* Update the Readme with the new settings (portal)
* Update values-production.yaml with the new settings

On the default values - 

  global.databaseUseSSL: true
  global.databaseRequireSSL: false

Will these work if SSL is not available? (if not suggest defaults are false.)
Has this been tested with the demo database?

**Comment by mohsinkhanbrcm** [comment]
> @mohsinkhanbrcm please clean up new line changes

done 👍🏼

**Review by APIM-KiranVaddadi — COMMENTED** [review]
Are these changes applicable for 5.0?

**Pull request closed without merging**
