### PR TITLE
[Chart/Gateway][Chart/Gateway-OTK] Add Sticky Session to Gateway Charts

### PR DESCRIPTION
**Pull request by alisterz**
**Description of the change**
Current Gateway chart doesn't not have sticky session enabled, which causes timeout issue when using Policy Manager with scaled (>2 pods)  gateway deployments

**Benefits**

Allow Policy Manager continue to work even when Gateway is scaled to multiple pods, no more timeout issues. 

**Drawbacks**
N/A

**Applicable issues**
N/A

**Additional information**
Identical approach Portal charts are using. 

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by jagsgill — APPROVED** [review]

**Review by jchanbcbc — APPROVED** [review]

**Review by Gazza7205 — CHANGES_REQUESTED** [review]
Sticky sessions should be configurable via values.yaml and optional.

**Comment by alisterz** [comment]
> Sticky sessions should be configurable via values.yaml and optional.

intention was to have it enabled by default so when ppl scale up GW, Policy Manager still works. 

Is there a way to enable it only for like 9443 port instead for all server ports?

**Comment by amoghsa** [comment]
I agree with @Gazza7205 here. This needs to be optional and configurable via values.yaml, if customer wants to keep a closed environment they should be able to keep it that way for security purposes.

**Review by Gazza7205 — COMMENTED** [review]
service.yaml

{{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}

values.yaml

sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
    timeoutSeconds: 10800


Default sessionAffinity not set, sessionAffinity set to ClientIP defaults to 10800 seconds, can be configured with sessionAffinityConfig. The indentation in this comment is incorrect..

**Review by Gazza7205 — APPROVED** [review]

**Pull request merged**
