### PR TITLE
[charts/portal] db-upgrade jobs as hooks

### PR DESCRIPTION
**Pull request by scottchc1**
**Description of the change**
move db-upgrade (and demo mysql) install into pre-install, pre-upgrade hook
mysql subchart require upgrade: chart version 8.8.16 (mysql app version 8.0.27)

**Benefits**
using hook to managed the re-creation of the db-upgrade jobs to work around immutable job limitation by helm 3. avoid manual job deletion for future helm upgrades (alleviate this issue: https://github.com/CAAPIM/apim-charts/tree/stable/charts/portal#helm-upgrade-failed-cannot-patch-db-upgrade-and-rbac-upgrade)

note: this benefit will be realized for future upgrades past v5.1, but from v5.0.x to 5.1 upgrade, the jobs still need to be manually deleted first since the jobs are not yet controlled by hooks in v5.0.x versions.

**Drawbacks**

- the jobs will always get re-created upon each helm upgrade, which may add a little bit of extra deployment time. although the execution will be very fast when there is little or nothing new to apply by the jobs.

**Applicable issues**
none

**Additional information**
mysql subchart change is required: depends on https://github.com/bitnami/charts/pull/8309
this is for the case of setupDemoDatabase = true, where the mysql container database must then also be installed early before the db-upgrade jobs run.

documentation update is required for following changed behaviour:

- helm install
  - demo db is deleted and recreated
  - upgrade jobs are deleted and recreated
  - the demo mysql container and upgrade jobs startup time is shifted from after helm install to during helm install. this means users will see about 3 minutes additional time where helm install runs and waits for their completion in pre-install hook stage before helm install returns a status.
  - helm install by default have up to 5 minutes timeout wait. if helm exits due to timeout, please inspect the deployment events and logs on kubernetes for reasons. 
- helm upgrade
  - demo db is preserved (this means demo db's data is preserved between upgrades)
  - upgrade jobs are deleted and recreated
- helm uninstall (upon uninstall, you need to manually remove these resources or delete the namespace entirely)
  - demo db is preserved
  - upgrade jobs are preserved

**Checklist** 
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by Gazza7205 — COMMENTED** [review]
The drawback is that customers have to wait over 3 minutes for the helm install command to return a success status. Unless I was prepared for this I would assume that something had gone wrong and cancel the install (the default helm timeout is 5m).

Is there a reason that we can't use post-install given that the database dependent containers will wait (based on the initContainers)?

**Comment by scottchc1** [comment]
tried post-install hook, but helm install also waits for post-install hook completion before returning a status

**Review by APIM-KiranVaddadi — COMMENTED** [review]
Do we need the hook delete policy? https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases

**Comment by scottchc1** [comment]
no we don't want additional delete policy. the jobs need to remain there after an install/upgrade because upgrade-verify (initContainer for most pods) looks for the jobs' status. ad hoc pod rescale/reroll will fail if the jobs aren't there. we only want to delete the jobs right before an upgrade, which is the default hook setting.

**Review by APIM-KiranVaddadi — APPROVED** [review]
LGTM

**Pull request merged**
