### PR TITLE
[charts/portal]US763040 Helm remove solr container

### PR DESCRIPTION
**Pull request by melil02**
**Description of the change**

removed solr container

**Benefits**

removed deprecated solr container

**Drawbacks**

None

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[charts/gateway]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by scottchc1 — COMMENTED** [review]
fine to me. please check with Gary why the lint failure

**Review by jb683638 — APPROVED** [review]
LGTM but also unsure of the lint failure.

**Comment by melil02** [comment]
@Gazza7205 could you please help us out? Looks like i ignored lint when i merged mysql change. I suspect this 
`WARN - portal/charts/mysql/templates/primary/statefulset.yaml contains an invalid StatefulSet (default.RELEASE-NAME-mysql) - startupProbe: Additional property startupProbe is not allowed`
line is causing issues

**Review by Gazza7205 — CHANGES_REQUESTED** [review]
It looks like develop/portal hasn't been updated against the stable branch in some time. The checks that are failing have since been updated/removed - validation starts at v1.17.5 (https://github.com/CAAPIM/apim-charts/blob/stable/.github/workflows/schema-validation.yaml)

Could you rebase develop/portal? 

Portal Version only needs to be incremented when there is a PR is against the Stable branch. The current published Chart version is 2.1.1.

I would also suggest adding a description of the Solr removal in the readme.md.

**Comment by scottchc1** [comment]
@Gazza7205 we've had saas only release from develop/portal, so need to bump chartVersion in develop sometimes. i don't think stable have to be limited in +1 increment only. there will be few cases of versions not immediately released to stable

**Pull request merged**
